apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dashboard-backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app: {{ .Release.Name }}-dashboard-backend