apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dashboard-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-dashboard-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-dashboard-backend
    spec:
      containers:
        - name: dashboard-backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5000
          command: ["python", "app.py"]